### ISSUE TITLE
Node version in github workflow is not correctly set

### ISSUE THREAD

**Issue by tilap** [azu/lerna-monorepo-github-actions-release#21]
Hi. Thanks for this great repo !

There is a misspell in the github workflow `publish.yml`. The action `actions/setup-node@v1` set the node version with `node-version` and not `node_version` (otherwise, it the the v10.X).

```
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12 # <-- this line
          registry-url: 'https://npm.pkg.github.com'
```

Have a nice day!
